// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarSharing.Entities
{
    public partial class Inspection
    {
        public int InspectionId { get; set; }
        public int CarId { get; set; }
        public DateTime InspectionDate { get; set; }
        public string InspectorName { get; set; }
        public string Result { get; set; }

        public virtual Car Car { get; set; }
    }
}