// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarSharing.Entities
{
    public partial class User
    {
        public User()
        {
            Employees = new HashSet<Employee>();
            Rentals = new HashSet<Rental>();
        }

        public int UserId { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}